/*
  # Demo vehicle photography — local files, and the focal points to crop them by

  Two changes to the three demo vehicles, and nothing else.

  ## 1. `image_url` moves off the Pexels CDN

  The seed (`20260314142241_seed_demo_vehicles.sql`) set `image_url` to a live
  `images.pexels.com` URL at `w=800`. Two problems with that on a
  recruiter-facing demo:

    - it is a third-party runtime dependency — if Pexels changes a URL, rate
      limits, or goes down, the demo has no car in it;
    - 800px is below what `.photo-hero` needs. It renders page-width and crops,
      so an 800px source is visibly soft on a laptop and worse on a retina one.

  Licensed masters now live in `public/vehicles/<slug>/`, provenance recorded in
  `public/vehicles/CREDITS.md`. Paths are stable and generated by
  `photography/build_assets.py`, so replacing a photograph later is a file swap
  and does *not* need another migration.

  ## 2. `focal_point_y` gets a per-vehicle value

  `vehicles.focal_point_y` has existed since `20260314224013`. `.photo-hero`
  reads it as `--focal-y` and falls back to `80%` when nothing is stored.

  That default is correct and deliberate: the product receives 3:4 phone
  snapshots with the car in the bottom half, which is the bug the v6 hero exists
  to fix. It is wrong for all three of these, because none of them is a phone
  snapshot. Values below are the vertical centre of the car in each frame, read
  off a gridded contact sheet (see `CREDITS.md`).

  `focal_point_x` is deliberately left alone. All three cars are horizontally
  centred, and the hero anchors x at 50% regardless.

  ## Why this is a new migration and not an edit

  The seed has already run against the live database. Editing it would change
  nothing in any environment that matters and would quietly diverge the file
  from the rows it produced.

  ## Idempotent

  Guarded on `is_demo` and on the known ids. Re-running is a no-op after the
  first apply. Does not touch user vehicles.
*/

DO $$
DECLARE
  v1_id uuid := 'a1000000-0000-0000-0000-000000000001'::uuid;  -- 2018 Honda Accord
  v2_id uuid := 'a2000000-0000-0000-0000-000000000002'::uuid;  -- 2020 Subaru WRX
  v3_id uuid := 'a3000000-0000-0000-0000-000000000003'::uuid;  -- 2019 BMW M3
BEGIN

  UPDATE vehicles
     SET image_url     = '/vehicles/accord/hero-3x2.jpg',
         focal_point_y = 72
   WHERE id = v1_id AND is_demo = true;

  UPDATE vehicles
     SET image_url     = '/vehicles/wrx/hero-3x2.jpg',
         focal_point_y = 58
   WHERE id = v2_id AND is_demo = true;

  UPDATE vehicles
     SET image_url     = '/vehicles/m3/hero-3x2.jpg',
         focal_point_y = 56
   WHERE id = v3_id AND is_demo = true;

END $$;
